import { browser } from "#imports";
import { newId, type CreatePayload, type SyncOperation } from "@syncer/shared";
import { isApplyingRemotely, wasAppliedBySync } from "./loop-guard";
import { loadState, updateState, type SyncState } from "./storage";
import { kindOf as classifyNode } from "./tree-mirror";

interface BookmarkEventNode {
  id: string;
  title: string;
  url?: string;
  parentId?: string;
  index?: number;
  children?: unknown[];
}

/**
 * Registers local bookmark change listeners that translate user-initiated
 * changes into sync operations. Changes generated by the synchronization
 * itself are recognized through the loop guard and never enqueued.
 */
export function registerBookmarkListeners(): void {
  browser.bookmarks.onCreated.addListener((id, bookmark) => {
    void handleCreated(id, bookmark as unknown as BookmarkEventNode);
  });

  browser.bookmarks.onChanged.addListener((id, changeInfo) => {
    void handleChange(id, changeInfo);
  });

  browser.bookmarks.onMoved.addListener((id, moveInfo) => {
    void handleMove(id, moveInfo);
  });

  browser.bookmarks.onRemoved.addListener((id, removeInfo) => {
    void handleRemove(id, removeInfo as unknown as { node: BookmarkEventNode });
  });
}

function isSyncGenerated(browserId: string): boolean {
  return isApplyingRemotely() || wasAppliedBySync(browserId);
}

async function handleCreated(browserId: string, bookmark: BookmarkEventNode): Promise<void> {
  if (!browserId || isSyncGenerated(browserId)) return;
  const state = await loadState();

  const parentBrowserId = bookmark.parentId ?? "";
  const parentGlobalId = state.browserToId[parentBrowserId];
  const parentKey =
    parentGlobalId ??
    Object.entries(state.rootMapping).find(([, browserRoot]) => browserRoot === parentBrowserId)?.[0];
  if (!parentKey) {
    console.debug("ignoring create under unmapped parent", parentBrowserId);
    return;
  }

  const globalId = state.browserToId[browserId];
  if (globalId) {
    // Already known (e.g. adopted moments ago); nothing to do.
    return;
  }

  // Bookmark nodes in onCreated events never carry a children array; use
  // url/type to classify instead.
  const classified = classifyNode(bookmark);
  if (classified === "separator") return;
  const isFolder = classified === "folder";
  const entityId = newId();

  await updateState((current) => {
    const payload: CreatePayload = {
      kind: isFolder ? "folder" : "bookmark",
      parentId: parentKey,
      title: bookmark.title,
      position: bookmark.index ?? 0,
    };
    if (!isFolder) payload.url = bookmark.url || "about:blank";

    current.pendingOps.push({
      operationId: newId(),
      userId: current.userId ?? "",
      deviceId: current.deviceId ?? "",
      entityId,
      type: "CREATE",
      payload,
      timestamp: Date.now(),
    });
    current.idToBrowser[entityId] = browserId;
    current.browserToId[browserId] = entityId;
  });
}

async function handleChange(
  browserId: string,
  changeInfo: { title: string; url?: string },
): Promise<void> {
  if (isSyncGenerated(browserId)) return;
  const state = await loadState();
  const entityId = state.browserToId[browserId];
  if (!entityId || !state.idToBrowser[entityId]) return;

  await updateState((current) => {
    current.pendingOps.push({
      operationId: newId(),
      userId: current.userId!,
      deviceId: current.deviceId!,
      entityId,
      type: "UPDATE",
      payload: {
        title: changeInfo.title,
        ...(changeInfo.url !== undefined ? { url: changeInfo.url } : {}),
      },
      timestamp: Date.now(),
    });
  });
}

async function handleMove(
  browserId: string,
  moveInfo: { parentId: string; index: number },
): Promise<void> {
  if (isSyncGenerated(browserId)) return;
  const state = await loadState();
  const entityId = state.browserToId[browserId];
  if (!entityId) return;

  const parentGlobalId = state.browserToId[moveInfo.parentId];
  const parentKey =
    parentGlobalId ??
    Object.entries(state.rootMapping).find(([, browserRoot]) => browserRoot === moveInfo.parentId)?.[0];
  if (!parentKey) return;

  await updateState((current) => {
    current.pendingOps.push({
      operationId: newId(),
      userId: current.userId!,
      deviceId: current.deviceId!,
      entityId,
      type: "MOVE",
      payload: { parentId: parentKey, position: moveInfo.index },
      timestamp: Date.now(),
    });
  });
}

async function handleRemove(browserId: string, removeInfo: { node: BookmarkEventNode }): Promise<void> {
  if (isSyncGenerated(browserId)) return;
  const state = await loadState();
  const entityId = state.browserToId[browserId];

  await updateState((current) => {
    purgeMappings(current, browserId, removeInfo.node);
    if (entityId && current.idToBrowser[entityId] !== undefined) {
      current.pendingOps.push({
        operationId: newId(),
        userId: current.userId!,
        deviceId: current.deviceId!,
        entityId,
        type: "DELETE",
        payload: {},
        timestamp: Date.now(),
      });
    }
  });
}

function purgeMappings(state: SyncState, browserId: string, node: BookmarkEventNode): void {
  const globalId = state.browserToId[browserId];
  if (globalId) delete state.idToBrowser[globalId];
  delete state.browserToId[browserId];
  for (const child of node.children ?? []) {
    const childNode = child as BookmarkEventNode;
    purgeMappings(state, childNode.id, childNode);
  }
}
